services:
  pgtemp:
    container_name: pgtemp
    image: postgres:alpine
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  owm-dispatcher:
    container_name: owmd
    image: owmd:0.1.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://pgtemp:5432/db
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
    depends_on:
      - pgtemp